#!/bin/bash

#PBS -A lsa_fluxm
#PBS -l qos=flux
#PBS -q fluxm
#PBS -M karepker@umich.edu
#PBS -N students
#PBS -l procs=1,walltime=8:00:00,mem=32gb
#PBS -V

WORKING_DIR=/tmp/$PBS_JOBID
PROJECT_ROOT=/afs/umich.edu/users/k/a/karepker/projects/eecs/443/
mkdir $WORKING_DIR


cp ${PROJECT_ROOT}/data/course.record.tab $WORKING_DIR
cp ${PROJECT_ROOT}/code/build/src/thesis $WORKING_DIR

cd $WORKING_DIR
mpirun ./thesis -stdin course.record.tab -t

rm -rf $working_dir
